blank_issues_enabled: false
contact_links:
  - name: Portfolio Site Support
    url: https://github.com/your-username/my-portfolio/discussions
    about: Please ask and answer questions here for non-bug related issues. 